//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//	 Runtime Version:4.0.30319.18449
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBeacon.SqlUpdate {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalBeacon.SqlUpdate.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT COUNT(*) FROM information_schema.tables WHERE table_catalog = DB_NAME() AND table_schema = (SELECT ISNULL(default_schema_name, &apos;dbo&apos;) FROM sys.database_principals WHERE name = USER) and table_name = &apos;SqlUpdate&apos;.
		/// </summary>
		internal static string CheckForDataUpdateObjectsSql {
			get {
				return ResourceManager.GetString("CheckForDataUpdateObjectsSql", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to CREATE TABLE [SqlUpdate](
		///	[Version] [nvarchar](20) NOT NULL,
		///	[PatchNumber] [int] NOT NULL,
		///	[Applied] [datetime] NOT NULL CONSTRAINT [DF_SqlUpdate_Applied] DEFAULT getdate(),
		///	[Module] [nvarchar](20) NOT NULL,
		///	CONSTRAINT [PK_DataUpdate] PRIMARY KEY CLUSTERED ([Module] ASC, [Version] ASC, [PatchNumber] ASC) ON [PRIMARY]
		///) ON [PRIMARY].
		/// </summary>
		internal static string CreateDataUpdateObjectsSql {
			get {
				return ResourceManager.GetString("CreateDataUpdateObjectsSql", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to INSERT INTO [SqlUpdate]([Version],[PatchNumber],[Module]) VALUES(@version, @patchNumber, @module).
		/// </summary>
		internal static string InsertPatchSql {
			get {
				return ResourceManager.GetString("InsertPatchSql", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT MAX([PatchNumber]) FROM [SqlUpdate] WHERE [Version] = @version AND [Module] = @module.
		/// </summary>
		internal static string QueryPatchNumberSql {
			get {
				return ResourceManager.GetString("QueryPatchNumberSql", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to SELECT DISTINCT [Version] FROM [SqlUpdate] WHERE [Module] = @module.
		/// </summary>
		internal static string QueryVersionSql {
			get {
				return ResourceManager.GetString("QueryVersionSql", resourceCulture);
			}
		}
	}
}
